language: node_js
node_js:
  - 12

addons:
  chrome: stable
  sauce_connect:
    username: 'pcalabria'
    access_key: "e946850e-c948-4838-a50a-1dc86590f2aa"
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script: npm run test:ci